package site

import (
	"net/url"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
)

// The original HTML editions were generated by the wiki's own builders, for
// the wiki's folder layout: they link to sibling .md files, to folders, and
// sometimes to anchors in GitHub's style. When they're published under
// /originals/, every link must still land somewhere real, so each <a href> is
// checked and, if it can't be resolved inside /originals/, pointed at the
// app's rendered page instead.

// Only real anchor tags: inside code examples "<" is escaped as "&lt;", so
// example markup like <a href="/x"> in a code block is never touched.
var reAnchorTag = regexp.MustCompile(`<a\s[^<>]*?href="([^"]*)"`)

var reIDAttr = regexp.MustCompile(`\sid="([^"]+)"`)

func idSet(html string) map[string]bool {
	ids := map[string]bool{}
	for _, m := range reIDAttr.FindAllStringSubmatch(html, -1) {
		ids[m[1]] = true
	}
	return ids
}

// resolveDoc maps a docs-relative target (file or folder) to a site URL.
func (b *Builder) resolveDoc(target string) (string, bool) {
	byMD, byOrg := b.docMaps()
	if u, ok := byMD[target]; ok {
		return u, true
	}
	if u, ok := byOrg[target]; ok {
		return u, true
	}
	if strings.HasSuffix(target, ".html") { // another edition of a rendered guide
		if u, ok := byMD[strings.TrimSuffix(target, ".html")+".md"]; ok {
			return u, true
		}
	}
	if path.Ext(target) == "" { // a folder: its README page, or the guide that owns it
		if u, ok := byMD[target+"/README.md"]; ok {
			return u, true
		}
		lr := &linkRewriter{byMD: byMD}
		return lr.byDir(target)
	}
	return "", false
}

// rewriteOriginal fixes the links of one original edition (docs-relative path orig).
func (b *Builder) rewriteOriginal(html, orig string, copied map[string]bool, origIDs func(string) map[string]bool) string {
	ownURL, _ := b.resolveDoc(orig)
	ownIDs := idSet(html)
	// a link from dist/originals/<dir>/ to a site path
	up := strings.Repeat("../", strings.Count("originals/"+path.Dir(orig)+"/", "/"))
	toApp := func(u, frag string) string {
		out := up + u
		if frag != "" {
			out += "#" + frag
		}
		return out
	}
	appHas := func(u, frag string) bool { return frag == "" || b.appIDs[u][frag] }

	return reAnchorTag.ReplaceAllStringFunc(html, func(tag string) string {
		m := reAnchorTag.FindStringSubmatch(tag)
		href := m[1]
		if href == "" || scheme.MatchString(href) || strings.HasPrefix(href, "//") || strings.HasPrefix(href, "/") {
			return tag // external, or not a local link
		}
		p, frag, _ := strings.Cut(href, "#")
		frag, _ = url.PathUnescape(frag)
		newHref := href
		switch {
		case p == "": // same-page anchor
			if !ownIDs[frag] && ownURL != "" && appHas(ownURL, frag) {
				newHref = toApp(ownURL, frag)
			}
		default:
			target := path.Clean(path.Join(path.Dir(orig), p))
			if copied[target] && (frag == "" || origIDs(target)[frag]) {
				break // fine as it is
			}
			if u, ok := b.resolveDoc(target); ok && appHas(u, frag) {
				newHref = toApp(u, frag)
			}
		}
		if newHref == href {
			return tag
		}
		return strings.Replace(tag, `href="`+href+`"`, `href="`+newHref+`"`, 1)
	})
}

// copyOriginals publishes the original editions with their links fixed.
func (b *Builder) copyOriginals() error {
	copied := map[string]bool{}
	for _, g := range b.M.Guides {
		for _, o := range g.Originals {
			copied[path.Clean(o)] = true
		}
	}
	cache := map[string]map[string]bool{}
	origIDs := func(o string) map[string]bool {
		if ids, ok := cache[o]; ok {
			return ids
		}
		data, _ := os.ReadFile(filepath.Join(b.DocsDir, o))
		cache[o] = idSet(string(data))
		return cache[o]
	}
	for o := range copied {
		data, err := os.ReadFile(filepath.Join(b.DocsDir, o))
		if err != nil {
			return err
		}
		out := b.rewriteOriginal(string(data), o, copied, origIDs)
		if err := writeFile(filepath.Join(b.OutDir, "originals", o), []byte(out)); err != nil {
			return err
		}
	}
	return nil
}
